### ISSUE TITLE
support for markdown table/ html table

### ISSUE THREAD

**Issue by sriramab** [COMOKIT/COMOKIT-Website#11]
It seems the website does not support markdown table as in this 65a6dbe. Could you please check, because the markdown table is a acceptable github format. May be the website builder does not support it? I also tried a html table , da1c65b , and it works on github, but not after  the website is built.  Thank you

**Comment by RoiArthurB** [comment]
Hi,

I think you just didn't wait long enough for the website to be rebuild and uploaded (see [here](https://github.com/COMOKIT/COMOKIT-Website/actions) to follow the auto build and release). As I see on the website, the table is displayed properly now :smile: 

https://comokit.org/docs/officialExtensions/C-Albatross
